-- Auto-generated by matugen, do not edit
return {
  base00 = "#0c160f",           -- background
  base01 = "#18221b", -- lighter background
  base02 = "#222c25", -- selection
  base03 = "#809685",           -- comments
  base04 = "#374b3d",   -- dark foreground
  base05 = "#dae6da",        -- default foreground
  base06 = "#b5ccba",-- light foreground
  base07 = "#dae6da",   -- lightest background
  base08 = "#ffb4ab",             -- red (errors)
  base09 = "#94d5a9",          -- orange (numbers)
  base0A = "#ceca74",         -- yellow (classes)
  base0B = "#d0cb54",           -- green (strings)
  base0C = "#4b4900", -- cyan (regex)
  base0D = "#4b4900",-- blue (functions)
  base0E = "#0c5130",-- purple (keywords)
  base0F = "#93000a",   -- deprecated
}
