# --- Basic UI ---
foreground            #dae6da
background            #0c160f
selection_foreground  #ebe68d
selection_background  #4b4900
cursor                #d0cb54
cursor_text_color     #343200
url_color             #94d5a9

# --- Windows & Borders ---
active_border_color   #d0cb54
inactive_border_color #374b3d
bell_border_color     #ffb4ab

# --- Tab Bar ---
active_tab_foreground   #ede76d
active_tab_background   #4b4900
inactive_tab_foreground #b5ccba
inactive_tab_background #374b3d

# --- Terminal Colors (ANSI) ---

# Black
color0 #0c160f
color8 #809685

# Red (Errors/Warnings)
color1 #ffb4ab
color9 #93000a

# Green (Success/Executables)
color2  #d0cb54
color10 #4b4900

# Yellow (Warnings/Special)
color3  #94d5a9
color11 #0c5130

# Blue (Folders/Information)
color4  #ceca74
color12 #4b4900

# Magenta
color5  #374b3d
color13 #aff2c4

# Cyan
color6  #ebe68d
color14 #ede76d

# White
color7  #dae6da
color15 #b5ccba
