# --- Basic UI ---
foreground            #f5dfcc
background            #1c1107
selection_foreground  #ffdada
selection_background  #723338
cursor                #ffb2b6
cursor_text_color     #5f121f
url_color             #fcb975

# --- Windows & Borders ---
active_border_color   #ffb2b6
inactive_border_color #59422c
bell_border_color     #ffb4ab

# --- Tab Bar ---
active_tab_foreground   #ffdada
active_tab_background   #7d2934
inactive_tab_foreground #e1c1a4
inactive_tab_background #59422c

# --- Terminal Colors (ANSI) ---

# Black
color0 #1c1107
color8 #a88b71

# Red (Errors/Warnings)
color1 #ffb4ab
color9 #93000a

# Green (Success/Executables)
color2  #ffb2b6
color10 #7d2934

# Yellow (Warnings/Special)
color3  #fcb975
color11 #693c00

# Blue (Folders/Information)
color4  #ffb2b6
color12 #723338

# Magenta
color5  #59422c
color13 #ffdcbd

# Cyan
color6  #ffdada
color14 #ffdada

# White
color7  #f5dfcc
color15 #e1c1a4
