# --- Basic UI ---
foreground            #e1e1ef
background            #11131c
selection_foreground  #baeaff
selection_background  #004d62
cursor                #60d4fe
cursor_text_color     #003545
url_color             #b7c4ff

# --- Windows & Borders ---
active_border_color   #60d4fe
inactive_border_color #424659
bell_border_color     #ffb4ab

# --- Tab Bar ---
active_tab_foreground   #baeaff
active_tab_background   #004d62
inactive_tab_foreground #c2c5dd
inactive_tab_background #424659

# --- Terminal Colors (ANSI) ---

# Black
color0 #11131c
color8 #8c8fa6

# Red (Errors/Warnings)
color1 #ffb4ab
color9 #93000a

# Green (Success/Executables)
color2  #60d4fe
color10 #004d62

# Yellow (Warnings/Special)
color3  #b7c4ff
color11 #364379

# Blue (Folders/Information)
color4  #89d0ed
color12 #004d62

# Magenta
color5  #424659
color13 #dde1ff

# Cyan
color6  #baeaff
color14 #baeaff

# White
color7  #e1e1ef
color15 #c2c5dd
