# --- Background and Foreground ---
# background            #1e1e1e
# foreground            #d4d4d4

# --- Selection Colors ---
# selection_background  #3e3e3e
# selection_foreground  #ffffff

# --- Cursor ---
# cursor                #cccccc
# cursor_text_color     #1e1e1e

# BEGIN_KITTY_THEME
# Matugen
include themes/Matugen.conf
font_family JetBrainsMono Nerd Font Regular
# END_KITTY_THEME
# --- Window Padding (Optional, for a cleaner look) ---
window_padding_width  10
allow_remote_control yes
listen_on unix:/tmp/mykitty


