# These placeholders will be replaced by Matugen hex codes
# ~/.config/matugen/hyprland.module
general {
    col.active_border = rgba(d0cb54ff) rgba(ceca74ff) 45deg
    col.inactive_border = rgba(374b3dff)
}

group {
    col.border_active = rgba(d0cb54ff)
    col.border_inactive = rgba(374b3dff)
}
