# ~/.config/matugen/hyprlock.module
$primary = rgb(#d0cb54)
$on_primary = rgb(#343200)
$secondary = rgb(#ceca74)
$on_secondary = rgb(#343200)
$surface = rgb(#0c160f)
$on_surface = rgb(#dae6da)
$surface_variant = rgb(#374b3d)
$on_surface_variant = rgb(#b5ccba)
$error = rgb(#ffb4ab)
$on_error = rgb(#690005)
$outline = rgb(#809685)
