[ColorEffects:Disabled]
Color=#809686
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=#494900
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=#494900
BackgroundNormal=#17221b
DecorationFocus=#cccc57
DecorationHover=#494900
ForegroundActive=#cccc57
ForegroundInactive=#809686
ForegroundLink=#91d5ac
ForegroundNegative=#ffb4ab
ForegroundNeutral=#cbcb76
ForegroundNormal=#d9e6db
ForegroundPositive=#91d5ac
ForegroundVisited=#045232

[Colors:Header]
BackgroundAlternate=#131e17
BackgroundNormal=#17221b
DecorationFocus=#cccc57
DecorationHover=#494900
ForegroundActive=#cccc57
ForegroundInactive=#809686
ForegroundLink=#91d5ac
ForegroundNegative=#ffb4ab
ForegroundNeutral=#cbcb76
ForegroundNormal=#d9e6db
ForegroundPositive=#91d5ac
ForegroundVisited=#045232

[Colors:Selection]
BackgroundAlternate=#494900
BackgroundNormal=#cccc57
DecorationFocus=#cccc57
DecorationHover=#494900
ForegroundActive=#323200
ForegroundInactive=#e8e870
ForegroundLink=#91d5ac
ForegroundNegative=#93000a
ForegroundNeutral=#323200
ForegroundNormal=#323200
ForegroundPositive=#045232
ForegroundVisited=#045232

[Colors:Tooltip]
BackgroundAlternate=#222c25
BackgroundNormal=#2c3730
DecorationFocus=#cccc57
DecorationHover=#494900
ForegroundActive=#cccc57
ForegroundInactive=#809686
ForegroundLink=#91d5ac
ForegroundNegative=#ffb4ab
ForegroundNeutral=#cbcb76
ForegroundNormal=#d9e6db
ForegroundPositive=#91d5ac
ForegroundVisited=#045232

[Colors:View]
BackgroundAlternate=#131e17
BackgroundNormal=#0b160f
DecorationFocus=#cccc57
DecorationHover=#494900
ForegroundActive=#cccc57
ForegroundInactive=#809686
ForegroundLink=#91d5ac
ForegroundNegative=#ffb4ab
ForegroundNeutral=#cbcb76
ForegroundNormal=#d9e6db
ForegroundPositive=#91d5ac
ForegroundVisited=#045232

[Colors:Window]
BackgroundAlternate=#131e17
BackgroundNormal=#17221b
DecorationFocus=#cccc57
DecorationHover=#494900
ForegroundActive=#cccc57
ForegroundInactive=#809686
ForegroundLink=#91d5ac
ForegroundNegative=#ffb4ab
ForegroundNeutral=#cbcb76
ForegroundNormal=#d9e6db
ForegroundPositive=#91d5ac
ForegroundVisited=#045232

[General]
ColorScheme=MatugenColors
Name=Matugen Colors
shadeSortColumn=true

[KDE]
contrast=4
