# --- Basic UI ---
foreground            {{colors.on_surface.default.hex}}
background            {{colors.surface.default.hex}}
selection_foreground  {{colors.on_secondary_container.default.hex}}
selection_background  {{colors.secondary_container.default.hex}}
cursor                {{colors.primary.default.hex}}
cursor_text_color     {{colors.on_primary.default.hex}}
url_color             {{colors.tertiary.default.hex}}

# --- Windows & Borders ---
active_border_color   {{colors.primary.default.hex}}
inactive_border_color {{colors.surface_variant.default.hex}}
bell_border_color     {{colors.error.default.hex}}

# --- Tab Bar ---
active_tab_foreground   {{colors.on_primary_container.default.hex}}
active_tab_background   {{colors.primary_container.default.hex}}
inactive_tab_foreground {{colors.on_surface_variant.default.hex}}
inactive_tab_background {{colors.surface_variant.default.hex}}

# --- Terminal Colors (ANSI) ---

# Black
color0 {{colors.surface.default.hex}}
color8 {{colors.outline.default.hex}}

# Red (Errors/Warnings)
color1 {{colors.error.default.hex}}
color9 {{colors.error_container.default.hex}}

# Green (Success/Executables)
color2  {{colors.primary.default.hex}}
color10 {{colors.primary_container.default.hex}}

# Yellow (Warnings/Special)
color3  {{colors.tertiary.default.hex}}
color11 {{colors.tertiary_container.default.hex}}

# Blue (Folders/Information)
color4  {{colors.secondary.default.hex}}
color12 {{colors.secondary_container.default.hex}}

# Magenta
color5  {{colors.outline_variant.default.hex}}
color13 {{colors.on_tertiary_container.default.hex}}

# Cyan
color6  {{colors.on_secondary_container.default.hex}}
color14 {{colors.on_primary_container.default.hex}}

# White
color7  {{colors.on_surface.default.hex}}
color15 {{colors.on_surface_variant.default.hex}}
