{
  "wallpaper": "",
  "alpha": "100",
  "colors": {
    "color0":  "{{colors.surface.dark.hex}}",
    "color1":  "{{colors.error.default.hex}}",
    "color2":  "{{colors.primary.default.hex}}",
    "color3":  "{{colors.tertiary.default.hex}}",
    "color4":  "{{colors.secondary.default.hex}}",
    "color5":  "{{colors.tertiary.default.hex}}",
    "color6":  "{{colors.secondary_container.default.hex}}",
    "color7":  "{{colors.surface_container_highest.default.hex}}",
    "color8":  "{{colors.surface_container.default.hex}}",
    "color9":  "{{colors.error_container.default.hex}}",
    "color10": "{{colors.primary.default.hex}}",
    "color11": "{{colors.tertiary_container.default.hex}}",
    "color12": "{{colors.secondary.default.hex}}",
    "color13": "{{colors.tertiary.default.hex}}",
    "color14": "{{colors.secondary_container.default.hex}}",
    "color15": "{{colors.on_background.default.hex}}"
  },
  "special": {
    "background": "{{colors.surface.dark.hex}}",
    "foreground": "{{colors.on_background.default.hex}}",
    "cursor":     "{{colors.primary.default.hex}}"
  }
}
